// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const browser: typeof import('wxt/browser')['browser']
  const cleanTitleForSearch: typeof import('C:/Users/yidir/Desktop/Code/GOG_DL/utils/slug')['cleanTitleForSearch']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const extractSlugFromUrl: typeof import('C:/Users/yidir/Desktop/Code/GOG_DL/utils/slug')['extractSlugFromUrl']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const findGameAvailability: typeof import('C:/Users/yidir/Desktop/Code/GOG_DL/utils/api')['findGameAvailability']
  const getGameTitleFromDOM: typeof import('C:/Users/yidir/Desktop/Code/GOG_DL/utils/dom')['getGameTitleFromDOM']
  const getSlugCandidates: typeof import('C:/Users/yidir/Desktop/Code/GOG_DL/utils/slug')['getSlugCandidates']
  const injectOrUpdateInstallButton: typeof import('C:/Users/yidir/Desktop/Code/GOG_DL/utils/dom')['injectOrUpdateInstallButton']
  const injectScript: typeof import('wxt/client')['injectScript']
  const observeUrlChanges: typeof import('C:/Users/yidir/Desktop/Code/GOG_DL/utils/dom')['observeUrlChanges']
  const storage: typeof import('wxt/storage')['storage']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { GameCheckResponse } from 'C:/Users/yidir/Desktop/Code/GOG_DL/utils/api'
  import('C:/Users/yidir/Desktop/Code/GOG_DL/utils/api')
}
